@extends('web.template.layout')

@section('title', 'Terms and Conditions')

@section('content')
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <!-- <div class="main-content"> -->
            <div class="page-content">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-lg-10">
                            <div class="text-center text-muted my-5">
                                <h1>Terms And Conditions</h1>
                            </div>
                            <div class="cms-content">
                                <p>This Subscription Agreement (hereinafter “Agreement”) is a legal contract between you, (hereinafter referred to as “Subscriber”) and Mednero LLC with its principal place of business located at Dubai , UAE (hereinafter referred to as “Mednero”), for access to the Mednero Software. BE SURE TO CAREFULLY READ AND UNDERSTAND ALL OF THE RIGHTS AND RESTRICTIONS DESCRIBED IN THIS AGREEMENT BEFORE USING THE Mednero SOFTWARE. BY USING THE Mednero SOFTWARE, YOU INDICATE YOUR PERSONAL ACCEPTANCE AND YOUR CONCURRENCE TO BE BOUND BY THE TERMS OF THIS AGREEMENT. IF YOU DO NOT AGREE TO THE TERMS OF THIS AGREEMENT, PLEASE DO NOT USE THE Mednero SOFTWARE.</p>
                                <p>Subscriber hereby acknowledges that Mednero has designed and developed certain proprietary software defined below as Mednero Software to be used by individuals/establishments looking for patient relationship management, software solutions; and associated hardware(s); and that Mednero intends to make available such Mednero Software, to the Subscriber(s) to enable the Subscriber(s) to upgrade its Outpatient department (OPD) in order to attract and delight patients, facilitate and manage (i) SMS and web based appointment booking system; (ii) doctor schedule and queue management; (iii) actionable patient contact base; and (iv) patient communication system for follow-up visit and alerts in order to improve patient satisfaction (v) improve conversion from out-patient to in-patient (“Purpose”). The Subscriber, being a third party / end customer, desires to use the Mednero Software for the Purpose, and not for redistribution.</p>
                                <h3>1. Definitions</h3>
                                <ol>
                                    <li>“Mednero Software” shall mean, collectively or individually, the software created/ designed by Mednero identified in Exhibit A of this Agreement that is provided to the Subscriber(s) on a subscription basis for the Purpose, including the Updates (defined below).</li>
                                    <li>“Updates” shall mean enhancements, bug fixes, updates and new versions made to the Mednero Software by Mednero and provided to the Subscriber by Mednero.</li>
                                    <li>“Upgrades” shall mean replacement of the Mednero Software with a newer or better version in order to bring the system up to date or improve the characteristics of the Mednero Software.</li>
                                </ol>
                                <h3>2. Intellectual property rights.</h3>
                                <ol>
                                    <li><b>Ownership.</b> Mednero retains all right, title and interest in and to and ownership of all Mednero Software, to all Updates and all modifications and the intellectual property rights thereto. Mednero does not transfer either the title or the intellectual property rights of the Mednero Software and its subscription services to the Subscriber(s).</li>
                                    <li><b>Preservation of Mednero’s Notices.</b> The Subscriber agrees not to (and not to allow others to) remove, alter, cover over, or deface Mednero’s proprietary notices which appear in or in connection with the Mednero Software as provided by Mednero to the Subscriber under this Agreement. Additionally, Mednero may include Subscriber’s name and/or logo within its list of customers for general promotional purposes.</li>
                                    <li><b>Subscription to the Subscriber.</b> Subject to all limitations and restrictions contained herein, Mednero grants to the Subscriber a subscription, software as a service (‘SaaS’), non-exclusive, and non-transferable right to access and operate the object code form of the Mednero Software, as hosted by Mednero (“Use”). Subscriber shall have a limited right and license to Use the Mednero Software solely for its internal purposes, to perform the functions described under Exhibit A for the Purpose. Subscriber shall not allow any website that is not fully owned by the Subscriber to frame, syndicate, distribute, replicate, or copy any portion of the Subscriber’s website that provides direct or indirect access to the Mednero Software. Unless otherwise expressly permitted in this Agreement under Exhibit A, Subscriber shall not permit any subsidiaries, affiliated companies, or third parties to access the Mednero Software. The Subscriber shall be provided with log-in credentials to the Mednero Software by the Mednero representative.</li>
                                    <li><b>Implementation and Training.</b> Mednero shall initiate the implementation of the Mednero Software for the Subscriber which might include creating the segregated hosting environment and effecting necessary interfaces for the Mednero Software upon mutual agreement between the parties. The start date of the subscription period shall be referred to as the “Commencement Date” which is fifteen (15) from the date of clearance of the payments. Further, the Subscriber shall conduct the necessary training for the Subscriber’s Authorized Users (as defined below) and the administrator of the Mednero Software with respect to the use and operation of all modules or components of Mednero Software (“Implementation and Training”). The Subscriber shall ensure the availability of the Authorized Users for the referred training.</li>
                                    <li><b>Free Trial.</b> Mednero may offer at its discretion, a free trial of the Mednero Software for a specified time period. During such trial period, the Subscriber shall be bound by the terms of this Agreement and any applicable law, regulation and generally accepted practices or guidelines in the relevant jurisdictions. Any data which the Subscriber enters into the Mednero Software, and any customizations made to the Mednero Software by or for the Subscriber, during the Subscriber’s free trial will be permanently lost at the expiry of the specified time period unless the Subscriber Upgrades his/her/its subscription to one of the paid subscription plans. Mednero does not provide any warranty during the trial period.</li>
                                    <li><b>Customization to the Mednero Software.</b> Mednero has the sole right to modify any feature or customize them at its discretion and there shall be no obligation to honor customization requests of the Subscriber.</li>
                                    <li><b>Functionality Changes.</b> Mednero reserves the right to add new functionality and modify existing functionality to the Mednero Software as and when it deems fit, and make any such changes available in newer versions of the Mednero Software or native mobile application or all of these at its discretion. The Subscriber will be duly notified upon release of such newer versions and Mednero reserves the right to automatically Upgrade all its users, including the Subscriber, to the latest version of the Mednero Software as and when Mednero deems fit. Mednero reserves the right to extend and withdraw the “Book” functionality to the Subscriber at Mednero’s sole discretion. The terms and conditions pertaining to the Book functionality is more fully described in Schedule No. 3 located at https://www.Mednero.com/company/terms.</li>
                                    <li><b>Subscriber Information.</b> Any communication sent by or through Mednero or the Mednero Software to the clients or customers of the Subscriber is based solely on information uploaded by the Subscriber on the Mednero Software. The accuracy and completeness of such information (including but not limited to contact details of the client or customer) is the sole responsibility of the Subscriber. Mednero will not be responsible for the incompleteness or inaccuracy of such information, including if as a result of such inaccuracy, a communication is sent to an unintended recipient.</li>
                                    <li><b>Additional Restrictions.</b> In no event shall the Subscriber disassemble, decompile, or reverse engineer the Mednero Software or permit others to do so.  Disassembling, decompiling, and reverse engineering include, without limitation: (i) converting the Mednero Software from a machine-readable form into a human-readable form; (ii) disassembling or decompiling the Mednero Software by using any means or methods to translate machine-dependent or machine-independent object code into the original human-readable source code or any approximation thereof; (iii) examining the machine-readable object code that controls Mednero Software’s operation and creating the original source code or any approximation thereof by, for example, studying Mednero Software’s behavior in response to a variety of inputs; or (iv) performing any other activity related to the Mednero Software that could be construed to be reverse engineering, disassembling, or decompiling.  The Subscriber agrees to immediately report to Mednero any unauthorized use or infringement of the Mednero Software that comes to its attention</li>
                                    <li><b>Authorized Users.</b> Unless otherwise specifically provided in the Agreement, “Authorized Users” will only consist of: (i) employees or consultants of the Subscriber, and (ii) subject to Section 5 (“Confidentiality”), third party contractors of the Subscriber who do not compete with Mednero (“Permitted Contractors”). Permitted Contractors may Use the Mednero Software only at the Subscriber’s place of business and/or the mobile application or in the presence of Subscriber personnel. Subscriber is fully liable for the acts and omissions of Permitted Contractors under this Agreement.</li>
                                    <li><b>Feedback</b> Subscriber acknowledges that the Mednero Software shall include the ability for users of the Subscriber’s service (“End-Users”) to provide Feedback on such service using the Mednero Software. Subscriber acknowledges that Mednero shall be entitled to, in its sole discretion, to publish or not publish such Feedback or to retain or not retain such Feedback and to moderate such Feedback, as required. “Feedback” for the purposes of this Agreement shall mean feedback, ratings and review provided by End-Users to the Subscriber’s service made available by Mednero on the Mednero Software. Any communication sent by the Subscriber to its clients or customers (whether or not End-Users) based on information collected by the Subscriber of its clients or customers will be sole responsibility of the Subscriber. The Subscriber must ensure accuracy of such communication sent, and must ensure that it is sent to the intended recipient.</li>
                                </ol>
                                <h3>3. Technical Support.</h3>
                                <ol>
                                    <li><b>Subscriber Support.</b> Mednero provides, at its discretion basic support for the Mednero Software subscribed by the Subscriber at no additional charge, and/or upgraded support if purchased separately and will use commercially reasonable efforts to make the subscription services available from 10 AM to 6.30 PM, Monday through Saturday excluding national holidays, except for (i) planned downtime (for which Mednero shall give at least eight (8) hours’ notice to the Subscribe(s) and which Mednero shall schedule to the extent practicable during the weekend hours from 6:00 p.m. regional’s  Standard Time ( Friday to 6:00 a.m. regional’s Standard Time Monday, or (ii) any unavailability caused by circumstances beyond Mednero’s reasonable control, including without limitation, acts of God, acts of government, flood, fire, earthquakes, civil unrest, acts of terror, strikes or other labour problems, or internet service provider failures or delays.</li>
                                </ol>
                                <h3>3. Confidentiality</h3>
                                <ol>
                                    <li><b>Confidential Information.</b> The parties to this Agreement undertake to retain in confidence all information disclosed to the other party in relation to this Agreement that the disclosing party has designated as being confidential in writing or if disclosed orally, or if, designated as confidential at the time of such disclosure and reduced to writing conspicuously marked as confidential and sent to such other party within thirty (30) days thereof (“Confidential Information“). The terms and conditions of this Agreement including its Exhibits shall be considered Confidential Information.</li>
                                    <li><b>Exclusions.</b> “Confidential Information” will not include information that: (a) is or becomes generally known or available by publication, commercial use or otherwise through no fault of the receiving party; (b) the receiving party can demonstrate to have had rightfully in its possession and without restriction, prior to disclosure hereunder; (c) is independently developed by the receiving party without use of the disclosing part’s Confidential  Information, as can be shown by tile written records of the receiving party; (d) is lawfully obtained from a third party who has the right to make such disclosure; or (e) is released for publication by the disclosing party in writing.  A receiving party also may disclose disclosing party’s Confidential Information to the extent required by a court or other governmental authority, provided that the receiving party promptly notifies the disclosing party of the disclosure requirement and cooperates with the disclosing party (at the latter’s expense and at its request) to resist or limit the disclosure.</li>
                                    <li><b>Protection of Confidential Information.</b> Each party agrees to protect the other party’s Confidential Information to the same extent that it protects its own confidential information of a similar nature and shall take all reasonable precautions to prevent any unauthorized disclosure of Confidential Information to third parties. A party may disclose other party’s Confidential Information to its directors, officers, employees and third party contractor(s) (“Representatives”) on a need to know basis and to the extent necessary for the purpose of this Agreement. If a party provides Confidential Information of the other party to its Representatives, then it will ensure that such Representatives have entered into a written confidentiality agreement with the part providing such information to the Representatives protecting such Confidential Information from unauthorized disclosure or improper use. Obligations of confidentiality under this Agreement shall survive the termination or expiration of the Agreement for a period of three (3) years; save for Confidential Information constituting trade secrets, in which event the obligations shall subsist indefinitely.</li>
                                </ol>
                                <h3>5. Representations and Warranties.</h3>
                                <ol>
                                    <li><b>By the Subscriber.</b> The Subscriber represents and warrants that the (a) Subscriber is 18 years of age or older and has the right, authority and capacity under the applicable law to use the Mednero Software and enter into this Agreement; (b) Subscriber will not transfer (including by way of sublicense, lease, assignment or other transfer, including by operation of law) their log¬in and Account details or right to use the Mednero Software to any third party; (c) information given to Mednero or uploaded on the Mednero Software by the Subscriber will always be true, accurate, correct, complete and up to date, to the best of the Subscriber’s knowledge that the Subscriber has the necessary rights from the end-user to upload such information on the Mednero Software, including but not limited to end-user health records (“User Content”), and that such right from the end-user shall include an explicit right for Mednero to reflect and map the User Content with an account of such user as may be created by such user through the Mednero website and for Mednero to further store and use the User Content for the purposes of Mednero’s business and for providing such other services in the region and outside region, as may be applicable; (d) Subscriber will not use the Mednero Software for any unauthorized and unlawful purpose; (e) Subscriber will not engage in any activity that interferes with or disrupts the Mednero Software or the servers and networks which are connected to the Mednero Software; (f) Subscriber will not reproduce, duplicate, copy, transfer, license, rent, sell, trade or resell the Mednero Software for any purpose whatsoever; (g) comply with all laws, regulations, and ordinances applicable to the Subscriber and its business and relating to the use of the Mednero Software under this Agreement; and (h) Subscriber will be subscribing to the Mednero Software only for the Purpose.</li>
                                    <li><b>By Mednero.</b> The Mednero Software provided by Mednero is provided “as is”, “as available” and Mednero makes no express or implied representations or warranties about its subscription services and/ or the Mednero Software or of merchantability or fitness for a particular purpose or use or non-¬infringement. Mednero does not authorize anyone to make a warranty on Mednero’s behalf and you may not rely on any statement of warranty as a warranty by Mednero.</li>
                                </ol>
                                <h3>6. Representations and Warranties.</h3>
                                <ol>
                                    <li><b>Mednero Indemnity.</b> Mednero shall indemnify, hold harmless and, defend the Subscriber from and against any and all final court awarded damages that are attributable to claim by a third party indicating that the Mednero Software infringes such third party intellectual property rights; provided that: (a) the Subscriber gives Mednero prompt notice in writing of any such suit and permits Mednero, through counsel of its choice, to answer the charge of infringement and defend such claim or suit; (b) the Subscriber provides information, assistance and authority to enable Mednero to defend such suit; and (c) Mednero shall not be responsible for any settlement made by the Subscriber without Mednero’s prior written permission provided, however that such permission shall not be unreasonably withheld.</li>
                                    <li><b>Exclusions.</b> Mednero shall have no liability set forth in Section 7.1 above: (a) for any claim or suit, where such claim or suit would have been avoided but for the effect on the Mednero Software caused by other software or hardware by the Subscriber; (b) for infringement of any intellectual property or proprietary rights arising in whole or in part from changes made to any Mednero Software by any party other than Mednero; and (c) where the allegedly infringing activity continues after the Subscriber has being notified thereof or has been informed of modifications that would have avoided the alleged infringement by Mednero.</li>
                                    <li><b>Subscriber Indemnity.</b> The Subscriber will defend, indemnify, and hold harmless Mednero, its corporate affiliates, or any of its or their respective directors, officers, owners, employees, agents, successors, and permitted assigns from and against any and all third-party claims, suits, proceedings, costs, and expenses (including, without limitation, attorneys’ fees) arising from or related to the Subscriber’s (a) breach of the confidentiality obligations, breach of intellectual property provisions and breach of representation and warranties provisions herein; (b) violation of any applicable law.</li>
                                </ol>
                                <h3>7. Limitation of Liability.</h3>
                                <p>LOL. IN NO EVENT SHALL Mednero BE LIABLE TO THE SUBSCRIBER FOR ANY LOST OR CORRUPTED DATA, DOWNTIME, LOST PROFITS, BUSINESS INTERRUPTION, REPLACEMENT SERVICE OR OTHER SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR INDIRECT DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THEORY OF LIABILITY, INCLUDING WITHOUT LIMITATION NEGLIGENCE AND (B) IN NO EVENT SHALL THE TOTAL AGGREGATE LIABILITY OF Mednero, FOR ALL CLAIMS ARISING OUT OF OR UNDER THIS AGREEMENT, EXCEED THE AMOUNT THAT THE SUBSCRIBER HAS PAID OR WILL PAY TO Mednero FOR THE Mednero SOFTWARE UNDER THIS AGREEMENT IN THE TWELVE (12) MONTHS PRECEDING THE MOST RECENT CLAIM.</p>
                                <h3>8. Term and Termination.</h3>
                                <ol>
                                    <li><b>Term.</b> This Agreement will remain in full force and effect for a period of one (1) year unless terminated by the parties in accordance with the provisions mentioned hereunder. This Agreement shall automatically renew for one (1) year period unless a party expresses his/her/its intention to terminate the agreement by providing sixty (60) days’ notice to the other party.</li>
                                    <li><b>Termination for Convenience.</b> The Subscriber can request for termination of his/her/its subscription of the Mednero Software at any time by providing sixty (60) days’ prior written notice to the address of Mednero mentioned in clause 10.3. During this sixty (60) ¬day period, Mednero will investigate and ascertain the fulfilment of any ongoing subscription services or pending dues related to subscription fees or any other fees by the Subscriber. Mednero reserves the right to terminate the association with the Subscriber at any time by providing thirty (30) days’ prior written notice to the Subscriber to the addresses mentioned in Clause 10.3.</li>
                                    <li><b>Termination for Cause.</b> Each party reserves the right to terminate this Agreement if the other party breaches a material obligation under this Agreement and such breach remains uncured for a period of thirty (30) days from the date of notification of the non-breaching party.</li>
                                    <li><b>Effect of termination.</b> On termination of this Agreement due to the reasons mentioned herein, Mednero reserves the right to immediately terminate the subscription of the Mednero Software to the Subscriber. Nothing contained in this Agreement shall restrict Mednero’s use of the data or right to publish information made available by the Subscriber in the public domain through the subscription services or any other platform managed by Mednero after the termination or expiry of this Agreement. After a 30 (thirty) day period from the date of termination of the Agreement, Mednero shall then provide/share any Subscriber data and shall thereafter, unless legally prohibited, delete all Subscriber’s data in its systems or otherwise in its possession or under its control. In cases where the Subscriber terminates the subscription voluntarily, it will be the sole responsibility of the Subscriber to make a copy of their data before terminating the subscription. ¬End-Users data will not be available after termination of subscription in such cases.</li>
                                </ol>
                                <h3>9. Term and Termination.</h3>
                                <ol>
                                    <li><b>Assignment.</b> The Subscriber may not assign this Agreement or any rights herein without the prior, written consent of Mednero.</li>
                                    <li><b>Waiver.</b> Failure or delay on the part of a party to exercise any right, power, privilege or remedy hereunder shall not constitute a waiver thereof. A waiver of default shall not operate as a waiver of any other default or of the same type of default on future occasions.</li>
                                    <li><b>Notices.</b> All notices and other communications pertaining to this Agreement shall be in writing and shall be deemed to have been given by a party hereto as set forth below and shall either be (a) personally delivered; (b) sent via postage prepaid certified mail, return receipt requested; (c) sent by nationally-recognized private express courier or (d) sent via fax provided that a confirmation copy is sent via one of the other methods described herein. Notices shall be deemed to have been given on the date of receipt if personally delivered or via fax, or two (2) days after deposit via certified mail or express courier. A party may change its address for purposes hereof by written notice to the other in accordance with the provision of this section. The addresses for the parties are as follows: <br>
                                        <b>Mednero:</b> Dubai ,UAE <br>
                                        <b>Subscriber:</b> As mentioned in the invoice
                                    </li>
                                    <li><b>Severability.</b> If any portion of this Agreement is held invalid, the parties agree that such invalidity sshall not affect the validity of the remaining portions of this Agreement, and the parties further agree to substitute for the invalid provision a valid provision that most closely approximates the economic effect and intent of the invalid provision.</li>
                                    <li><b>Independent Parties.</b> The parties acknowledge that neither party is an agent or employee of the other party, and that neither party has any authority to bind the other party to any agreement or obligation.</li>
                                    <li><b>Governing Law.</b> Any dispute, claim or controversy arising out of or relating to this Agreement, will be governed by the laws of  UAE and the courts in UAE shall have exclusive jurisdiction over any disputes arising out of or in relation to this Agreement.</li>
                                    <li><b>Headings.</b> Paragraph headings have been included in this Agreement merely for convenience of reference. They shall not be considered part of, or be used in interpreting, this Agreement.</li>
                                    <li><b>Counterparts.</b> This Agreement may be executed in two or more counterparts, each of which shall be deemed an original and all of which taken together shall constitute one and the same Agreement.</li>
                                    <li><b>Survival.</b> The provisions of Sections 2, 4, 5, 6, 7, 8, 9 and 10 shall survive expiration or termination of this Agreement for any reason.</li>
                                    <li><b>Entire Agreement.</b> This Agreement and the Exhibits attached hereto constitute the entire agreement between the parties with respect to the subject matter hereof and supersede all proposals, oral or written, all previous negotiations and all previous communications between the parties with respect thereto.</li>
                                    <li><b>Additional terms</b> Mednero reserves the right to modify this Agreement at any time without giving the Subscriber any prior notice. Subscriber’s use of the Mednero Software following any such modification constitutes Subscriber’s agreement to follow and be bound by this Agreement as modified. Any additional terms and conditions, disclaimers, privacy policies and other policies applicable to general and specific areas of the Mednero Software or to subscription services are also considered as part of this Agreement. By agreeing to these terms, Subscriber also agrees to the terms of use, which are available at Mednero.com/company/terms.</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                @include('web.template.footer-content-prime')
            </div>
            <!-- </div> -->
            <!-- end main content-->
@endsection